[package]
name = "raytracing"
version = "0.1.0"
authors = ["dams <damien.messner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.110.0"
image = "0.23.0"
